# Generated by Django 5.0.6 on 2024-09-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='period',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
