# Generated by Django 5.0.6 on 2024-09-05 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0002_alter_payment_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='period',
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_number', models.DecimalField(decimal_places=0, max_digits=2)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], default='1', max_length=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='week',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='digi.week'),
            preserve_default=False,
        ),
    ]
