# Generated by Django 5.0.6 on 2024-09-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0003_remove_payment_period_week_payment_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='status',
        ),
    ]
