# Generated by Django 5.0.6 on 2024-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0004_remove_week_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='collaborator_percentage',
            field=models.FloatField(),
        ),
    ]
