# Generated by Django 5.0.6 on 2024-12-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0005_alter_company_collaborator_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='collaborator_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='week',
            name='week_number',
            field=models.IntegerField(),
        ),
    ]
