# Generated by Django 5.0.6 on 2024-12-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0006_alter_company_collaborator_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='collaborator_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
