# Generated by Django 5.0.6 on 2024-12-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0007_week_collaborator_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='collaborator',
        ),
        migrations.AddField(
            model_name='week',
            name='year_number',
            field=models.IntegerField(default=0),
        ),
    ]
