# Generated by Django 5.0.6 on 2024-12-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0008_remove_week_collaborator_week_year_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='collaborator_percentage',
        ),
    ]
