# Generated by Django 5.0.6 on 2024-12-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0009_remove_week_collaborator_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Rejected')], default='1', max_length=1),
        ),
    ]
